- name: Disable default redis module
  ansible.builtin.shell: dnf module disable redis

- name: Eanble redis 7
  ansible.builtin.shell: dnf module enable redis:7

- name: install redis 7
  ansible.builtin.dnf:
    name: redis
    state: latest

- name: Update Redis conf listen addr from 127.0.0.1 to 0.0.0.0
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Update Redis conf protection mode to on
  ansible.builtin.lineinfile:
    path: /etc/mongod.conf
    regexp: 'protected-mode'
    line: 'protected-mode on'

- name: Enable and start service
  ansible.builtin.systemd_service:
    name: redis
    state: restarted
    enabled: yes
    
