- name: Retrive variables from previous tasks_from
  hosts: localhost
  vars_files:
    - var_file.yml
  vars:
     v1: "from vars"
  tasks:
    # - ansible.builtin.debug:
    #     msg: "{{ v1 }}"
    - ansible.builtin.debug:
        msg: "Hello "
    - ansible.builtin.debug:
         msg: "Hi"
    - ansible.builtin.debug:
        msg: "{{ v1 }}"
      # vars: 
      #   v1: "from tasks"


  # roles:
  #   - sample

# cli 
# tasks
# role
# Vars
