- name: Retrive variables from previous tasks_from
  hosts: localhost
  vars:
     v1: "from vars"
  tasks:
    vars: 
      v1: "From tasks"
    ansible.builtin.debug:
      msg: "{{ v1 }}"
     
      


    