- name: Retrive variables from previous tasks_from
  hosts: localhost
  vars_files:
    - vars_file.yml
  vars:
     v1: "from vars"
  tasks:
    # - ansible.builtin.debug:
    #     msg: "{{ v1 }}"
    - ansible.builtin.debug:
        msg: "Hello "
    - ansible.builtin.debug:
         msg: "Hi"
    - ansible.builtin.debug:
        msg: "{{ v1 }}"
      # vars: 
      #   v1: "from tasks"


  # roles:
  #   - sample

# cli 
# tasks
# role
#var file
# Vars
#defaults 


########## loops#########
- name: loops
  hosts: localhost
  tasks:
    - name: print
      debug:
        msg: fruit - {{ item }}
      loop:
        - {name: Apple, qunt: 100}
        - {name: Mango, qunt: 100}
        - {name: orange, qunt: 200}
