- name: disable default nginx
  ansible.builtin.shell: dnf module disable nginx -y

- name: Enable nginx 24 vaesion
  ansible.builtin.shell: dnf module enable nginx:24 -y 

- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    status: latest

- name: Copy nginx config file
  ansible.builtin.copy:
    source: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: start nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes

    


  