- name: Copy mongo repofile
  ansible.builtin.template:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install Mongo DB
  ansible.builtin.dnf:
    name: mongodb-org
    state: latest

- name: Update Mongo Config file
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: start Mongo services
  ansible.builtin.systemd_service:
    name: mongod
    state: restarted
    enabled: yes