- name: Install maven
  ansible.builtin.dnf:
    name: maven
    state: latest

- name: Include app prereq
  ansible.builtin.include_role:
    name: common
    tasks_from: apps-prereq

- name: Download dependences
  ansible.builtin.shell: mvn clean package; mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: "{{ app_path }}"

- name: Lode schema from common
  ansible.builtin.include_role:
    role: common
    tasks_from: schema

- name: load systemd from common
  ansible.builtin.include_role:
    role: common
    tasks_from: systemd


