- name: Copy Service file
  ansible.builtin.template:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service
  when: component == 'catalogue'

- name: start service
  ansible.builtin.systemd_service:
    name: catalogue
    state: restarted
    enabled: yes
    daemon-reload: yes
  when: component == 'catalogue'

- name: Copy Service file
  ansible.builtin.template:
    src: user.service
    dest: /etc/systemd/system/user.service
  when: component == 'user'

- name: start service
  ansible.builtin.systemd_service:
    name: user
    state: restarted
    enabled: yes
    daemon-reload: yes
  when: component == 'user'



- name: start service
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: yes
    daemon-reload: yes
  when: component == 'mysql'

- name: shipping service config
  when: component == "shipping"
  block:
    - name: copy shipping.service file
      ansible.builtin.template:
        src: shipping.service
        dest: /etc/systemd/system/shipping.service
    - name: enable & start service
      ansible.builtin.systemd_service:
        name: shipping
        state: restarted
        enabled: yes
        daemon-reload: yes

- name: cart service config
  when: component == "cart"
  block:
    - name: copy cart.service file
      ansible.builtin.template:
         src: cart.service
         dest: /etc/systemd/system/cart.service
    - name: enable & start service
      ansible.builtin.systemd_service:
        name: cart
        state: restarted
        enabled: yes
        daemon-reload: yes

- name: cart service config
  when: component == "rabbitmq"
  block:
    - name: enable & start service
      ansible.builtin.systemd_service:
        name: rabbitmq-server
        state: restarted
        enabled: yes
        daemon-reload: yes
